apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: monster-graph
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: Monster
    group: game.k8s.example
    spec:
      dungeonName: string | required=true
      index: integer | required=true
      hp: integer | required=true
      difficulty: string | default="normal"
    status:
      entityState: "${monsterState.data.entityState}"
      hp: "${monsterState.data.hp}"

  resources:
    - id: monsterState
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: "${schema.spec.dungeonName + '-monster-' + string(schema.spec.index)}"
          namespace: ${schema.metadata.namespace}
          labels:
            game.k8s.example/dungeon: ${schema.spec.dungeonName}
            game.k8s.example/entity: monster
            game.k8s.example/state: "${schema.spec.hp > 0 ? 'alive' : 'dead'}"
        data:
          entityState: "${schema.spec.hp > 0 ? 'alive' : 'dead'}"
          hp: "${string(schema.spec.hp)}"
